import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"> 
      <body className=' bg-t-secondary text-black bg-gradient-to-tr from-blue-800 to-purple-800'>
        <Header />
        {children} 
      </body>
    </html>
  )
}
